### ISSUE TITLE
/docker-entrypoint.sh: not found

### ISSUE THREAD

**Issue by asontha** [hbagdi/fly-kong#1]
Trying to use this to deploy kong to fly, but running into this error:

```
2023-06-30T19:28:01Z app[9080ee46f63748] bos [info]running kong's docker-entrypoint.sh...
2023-06-30T19:28:01Z app[9080ee46f63748] bos [info]/kong-fly.sh: 10: /docker-entrypoint.sh: not found
```

Where is /docker-entrypoint.sh?

**Comment by asontha** [comment]
If I run the image locally without using the Dockerfile and then `ls`, I don't see /docker-entrypoint.sh inside the image.

```
$ docker container list
CONTAINER ID   IMAGE                          COMMAND                  CREATED          STATUS                            PORTS                                                                          NAMES
c9b1e9c7677e   kong/kong-gateway:3.3-ubuntu   "/entrypoint.sh kong…"   11 seconds ago   Up 9 seconds (health: starting)   0.0.0.0:8000->8000/tcp, 8001-8004/tcp, 0.0.0.0:8443->8443/tcp, 8444-8447/tcp   gifted_lederberg
$ docker exec gifted_lederberg ls
bin
boot
dev
entrypoint.sh
etc
home
lib
media
mnt
opt
proc
root
run
sbin
srv
sys
tmp
usr
var
```

**Comment by asontha** [comment]
Heads up that I was able to get Kong running with these changes:

First copy the docker-entrypoint.sh into project directory from here: https://github.com/Kong/docker-kong/blob/507775715a22e419d1c7e42028f7c3b5d9cf0418/ubuntu/docker-entrypoint.sh

Note: Don't forget to `chmod XXX docker-entrypoint.sh` locally first

Next, update Dockerfile with the following contents:
```
FROM kong/kong-gateway:3.3-ubuntu
USER root
COPY kong-fly.sh /kong-fly.sh
COPY docker-entrypoint.sh /docker-entrypoint.sh
ENTRYPOINT /kong-fly.sh
```

then run `fly deploy` and it should work assuming the secrets were set up as explained in the guide.

**Comment by gAmUssA** [comment]
@asontha I updated instruction with #2 PR. Check it out
my fly app runs kong 3.3 on fly.io and configuration managed by Kong Konnect (rate limiting plugin is enabled)

```
 http kong-vikgamov-42.fly.dev/status/200

HTTP/1.1 200 OK
access-control-allow-credentials: true
access-control-allow-origin: *
connection: keep-alive
content-encoding: gzip
content-type: application/json; charset=utf-8
date: Fri, 07 Jul 2023 04:24:29 GMT
fly-request-id: 01H4Q9G8AHJA6NCVVR2FC5Y00X-lga
ratelimit-limit: 60
ratelimit-remaining: 59
ratelimit-reset: 31
server: Fly/a0b91024 (2023-06-13)
transfer-encoding: chunked
via: kong/3.3.1.0-enterprise-edition, 1.1 fly.io
x-kong-proxy-latency: 2
x-kong-upstream-latency: 278
x-ratelimit-limit-minute: 60
x-ratelimit-remaining-minute: 59

{
    "message": "OK"
}
```

**Comment by asontha** [comment]
Awesome! Will check it out and hopefully the changes get merged. Let me see what happens if I use entrypoint.sh. Would much rather use what's provided as part of the image.

**Comment by asontha** [comment]
Confirming that using your changes worked, thank you!
